name: photo_sharing_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  chat_bubbles: ^1.6.0
  permission_handler: ^11.3.1
  flutter_bloc: ^8.1.6

  flutter_spinkit: ^5.2.1
  get_it: ^8.0.2
  intl: 0.19.0
  http: ^1.2.2
  image_picker: 1.1.2
  image_picker_android: 0.8.12+13
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  share_plus: ^10.1.2
  flutter_riverpod: ^2.6.1
  flutter_redux: ^0.10.0
  path: ^1.9.0
  sqflite: 2.3.3+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  shared_preferences: ^2.3.2
  shared_preferences_android: 2.3.2
  flutter_local_notifications: ^18.0.1
  firebase_auth: 5.3.3
  firebase_core: 3.8.0
  firebase_storage: 12.3.2
  cloud_firestore: ^5.5.0
  firebase_database: ^11.1.5
  firebase_messaging: ^15.1.4
  flutter_smart_dialog: ^4.9.8+6
  url_launcher: ^6.3.1
  url_launcher_android: 6.3.10
  url_launcher_ios: 6.3.1
  social_sharing_plus: ^1.2.3
  collection: 1.18.0
  rxdart: 0.27.7
  sqflite_common: 2.5.4+3
  html: 0.15.4
  flutter_plugin_android_lifecycle: 2.0.20
  camera: 0.11.0+2
  camera_android_camerax: 0.6.10
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - assets/
 