name: photo_sharing_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  chat_bubbles: ^1.6.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  get_it: ^8.0.2
  http: ^1.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  keyboard_avoider: ^0.2.0
  flutter_riverpod: ^2.6.1
  flutter_redux: ^0.10.0
  path: ^1.9.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  shared_preferences: ^2.5.2
  flutter_smart_dialog: ^4.9.8+6
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  firebase_storage: ^12.4.3
  cloud_firestore: ^5.6.4
  firebase_messaging: ^15.2.3
  firebase_database: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  # integration_test:
  #   sdk: flutter
  # msix: ^3.16.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
 