// File generated by FlutterFire CLI.
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show
        defaultTargetPlatform,
        // kIsWeb,
        TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    print(defaultTargetPlatform);
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
        case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyBzbx03FNypH_QQC0jmu4aHXupUoAezoho',
      appId: '1:915215970623:android:caea9ce4118f6fc078638a',
      messagingSenderId: '915215970623',
      projectId: 'cameraapp-87770',
      storageBucket: 'cameraapp-87770.firebasestorage.app');
        static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyCB8lQfG60E_MPDKnVrgKZFwiYBYaOJ_VA',
      appId: '1:700244737798:ios:164a2bffe4e638218e6887',
      messagingSenderId: '700244737798',
      projectId: 'cameraapp-87770',
      storageBucket: 'cameraapp-87770.firebasestorage.app');
}
